# Generated by Django 6.0.4 on 2026-05-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_id', models.CharField(max_length=20, unique=True)),
                ('fact_name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('MBA', 'Management'), ('Physics', 'Physics')], max_length=50)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lab Instructor', 'Lab Instructor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ME', 'Mechanical Engineering'), ('MBA', 'Management'), ('Physics', 'Physics')], max_length=50)),
                ('program', models.CharField(choices=[('B.Tech CSE', 'B.Tech CSE'), ('B.Tech ME', 'B.Tech ME'), ('MBA', 'MBA'), ('BSc. Physics', 'BSc. Physics')], max_length=50)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_with', models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent')], default='Student', max_length=20)),
                ('date_interacted', models.DateField()),
                ('issue', models.CharField(choices=[('Less Attendance', 'Less Attendance'), ('Poor Performance', 'Poor Performance'), ('Discipline', 'Discipline'), ('Health', 'Health'), ('Other', 'Other')], default='Less Attendance', max_length=50)),
                ('interaction_type', models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('In-Person', 'In-Person'), ('Email', 'Email'), ('SMS', 'SMS'), ('Other', 'Other')], default='Call', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='api.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='api.student')),
            ],
        ),
    ]
