# Generated by Django 6.0.4 on 2026-06-19 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='interacted_with',
            field=models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='interaction_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Physical Meet', 'Physical Meet'), ('Whatsapp', 'Whatsapp'), ('SMS', 'SMS'), ('Other', 'Other')], default='Call', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='issue',
            field=models.CharField(choices=[('General', 'General'), ('Less Attendance', 'Less Attendance'), ('ERP Issue', 'ERP Issue'), ('Results', 'Results'), ('Class Not Attending', 'Class Not Attending'), ('Extra Class Required For Maths', 'Extra Class Required For Maths'), ('Exam Result', 'Exam Result'), ('Backlog', 'Backlog'), ('Other', 'Other')], default='Less Attendance', max_length=50),
        ),
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mappings', to='api.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mappings', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interacted', models.DateField()),
                ('interacted_with', models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Student', max_length=20)),
                ('issue', models.CharField(choices=[('General', 'General'), ('Less Attendance', 'Less Attendance'), ('ERP Issue', 'ERP Issue'), ('Results', 'Results'), ('Class Not Attending', 'Class Not Attending'), ('Extra Class Required For Maths', 'Extra Class Required For Maths'), ('Exam Result', 'Exam Result'), ('Backlog', 'Backlog'), ('Other', 'Other')], default='General', max_length=50)),
                ('interaction_type', models.CharField(choices=[('Call', 'Call'), ('Physical Meet', 'Physical Meet'), ('Whatsapp', 'Whatsapp'), ('SMS', 'SMS'), ('Other', 'Other')], default='Call', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_activities', to='api.student')),
            ],
        ),
    ]
